[workspace]
resolver = "2"
members = [
    "allocative/allocative",
    "allocative/allocative_derive",
    "gazebo/display_container",
    "gazebo/dupe",
    "gazebo/gazebo",
    "gazebo/gazebo_derive",
    "starlark",
    "starlark_derive",
]

[workspace.dependencies]
allocative = { version = "0.3", path = "allocative/allocative" }
allocative_derive = { version = "0.2", path = "allocative/allocative_derive" }
dupe = { version = "0.9.0", path = "gazebo/dupe" }
display_container = { version = "0.8.1", path = "gazebo/display_container" }
either = "1.8"
gazebo = { version = "0.8.1", path = "gazebo/gazebo" }
gazebo_derive = { version = "0.8.1", path = "gazebo/gazebo_derive" }
indenter = "0.3.3"

ctor = "0.1.26"
proc-macro2 = "1.0"
syn = "2"
quote = "1.0.3"
